// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB6Jlkf1YZSv_YglI_iX6bl73TJuKAoR0',
    appId: '1:140771179995:web:2227f773673c7639543bfe',
    messagingSenderId: '140771179995',
    projectId: 'littlecafe-2554c',
    authDomain: 'littlecafe-2554c.firebaseapp.com',
    storageBucket: 'littlecafe-2554c.appspot.com',
    measurementId: 'G-K9X4211EF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwA28uOkRa-GOI1sfNAusjLgOLh9okkKE',
    appId: '1:140771179995:android:0e2ef7cbdde04195543bfe',
    messagingSenderId: '140771179995',
    projectId: 'littlecafe-2554c',
    storageBucket: 'littlecafe-2554c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ie8M0cblsD_AYowKIstp_Pk2A0zE40M',
    appId: '1:140771179995:ios:0752f709525a55b3543bfe',
    messagingSenderId: '140771179995',
    projectId: 'littlecafe-2554c',
    storageBucket: 'littlecafe-2554c.appspot.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB6Jlkf1YZSv_YglI_iX6bl73TJuKAoR0',
    appId: '1:140771179995:web:7f7d7fdac6a455af543bfe',
    messagingSenderId: '140771179995',
    projectId: 'littlecafe-2554c',
    authDomain: 'littlecafe-2554c.firebaseapp.com',
    storageBucket: 'littlecafe-2554c.appspot.com',
    measurementId: 'G-TPQGTK89YQ',
  );
}
